TrajectoryPlannerROS:
  max_vel_x: 0.1
  min_vel_x: 0.05
  max_vel_theta: .15
  min_in_place_vel_theta: 0.05

  escape_vel: -0.05

  acc_lim_theta: .3
  acc_lim_x: .5
  acc_lim_y: .5

  holonomic_robot: false